default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 10
  username: postgres
  password: root

development: &development
  <<: *default
  database: kosento_development

test: &test
  <<: *default
  database: konsento_test

production: &production
  <<: *default
  pool: 20
  host: localhost # <%= ENV['KONSENTO_DATABASE_HOST'] %>
  password: konsentopassword # <%= ENV['KONSENTO_DATABASE_PASSWORD'] %>
  database: kosento_production
